# Generated by Django 3.2.9 on 2021-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_acc',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
