# Generated by Django 3.2.9 on 2021-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_google_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
