# Generated by Django 3.2.9 on 2021-11-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
