# Generated by Django 3.2.9 on 2021-11-08 20:13

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
