# Generated by Django 3.2.9 on 2021-11-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='birth_date',
        ),
    ]
