# Generated by Django 3.2.9 on 2021-11-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarManifacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='post',
            name='body_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fuel_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='owner_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='transmission',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('carmanifacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.carmanifacturer')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.carmodel'),
            preserve_default=False,
        ),
    ]
