# Generated by Django 3.2.9 on 2021-11-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='carmanifacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='market.carmanifacturer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
