# Generated by Django 3.2.9 on 2021-11-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.post'),
        ),
    ]
