# Generated by Django 3.2.9 on 2021-11-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_post_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carmodel', to='market.carmodel'),
        ),
    ]
