# Generated by Django 3.2.9 on 2021-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_post_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
