# Generated by Django 3.2.9 on 2021-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='displacement',
            field=models.IntegerField(null=True),
        ),
    ]
