# Generated by Django 3.2.9 on 2021-12-05 10:34

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_post_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/photos'),
        ),
    ]
