# Generated by Django 3.2.9 on 2021-12-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_alter_postimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
