# Generated by Django 3.2.9 on 2021-12-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_rename_image_postimage_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
