# Generated by Django 3.2.9 on 2021-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_rename_thumbnail_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fuel_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='transmission',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
