# Generated by Django 3.2.9 on 2021-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_alter_post_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
