# Generated by Django 3.2.9 on 2021-12-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carmodel', to='market.carmodel'),
        ),
    ]
